
title: title.pdf

title.pdf: title.tex ../sources/infos_titlepage.tex
	cd .. && pdflatex miscpages/title.tex
	mv ../title.pdf .
	rm ../title.*


resume: resume.pdf

resume.pdf: resume.tex
	cd .. && pdflatex miscpages/resume.tex
	mv ../resume.pdf .
	rm ../resume.*